name: coronavirus
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_statusbarcolor: ^0.2.3
  connectivity: ^0.4.8+2
  dio: ^3.0.9
  intl: ^0.16.1
  scoped_model: ^1.0.1
  json_annotation: ^3.0.0
  get_it: ^4.0.2
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.5
  fl_chart: ^0.9.4

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoLight
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 700
